### ISSUE TITLE
Translation failed when packaged added to Net Standard 2.0 project

### ISSUE THREAD

**Issue by evolcano** [Grizley56/GoogleTranslateFreeApi#17]
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleTranslateFreeApi.GoogleKeyTokenGenerator.<GetNewExternalKeyAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleTranslateFreeApi.GoogleKeyTokenGenerator.<GenerateAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleTranslateFreeApi.GoogleTranslator.<GetTranslationResultAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleTranslateFreeApi.GoogleTranslator.<TranslateLiteAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoogleTrans.translater.<Trans>d__0.MoveNext() in C:\Users\HMY\source\repos\stringCompare\GoogleTrans\translater.cs:line 21

  This exception was originally thrown at this call stack:
    [External Code]
    GoogleTrans.translater.Trans() in translater.cs

**Comment by d4n3436** [comment]
Google Translate changed the way the API works and now it uses a different endpoint to get the translations.
The library fails to get the translation because it can no longer get the token.

More info [here](https://github.com/ssut/py-googletrans/issues/234) and [here](https://github.com/ssut/py-googletrans/issues/234#issuecomment-722403955).
