### ISSUE TITLE
TranslateLiteAsync Error

### ISSUE THREAD

**Issue by janandojan** [Grizley56/GoogleTranslateFreeApi#19]
System.NotSupportedException
  HResult=0x80131515
  Message=**The method is no longer valid, or something went wrong**

   at GoogleTranslateFreeApi.GoogleKeyTokenGenerator.<GenerateAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GoogleTranslateFreeApi.GoogleTranslator.<GetTranslationResultAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GoogleTranslateFreeApi.GoogleTranslator.<TranslateAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by d4n3436** [comment]
There's a new Google Translate endpoint that you can use for free here: ssut/py-googletrans#268
