### ISSUE TITLE
Can not convert Array to String exception

### ISSUE THREAD

**Issue by viacheslav-men** [Grizley56/GoogleTranslateFreeApi#7]
While using your library, when awaiting for the TranslateAsync method sometimes an exception is thrown:

`Unhandled Exception: System.AggregateException: One or more errors occurred. (Can not convert Array to String.) ---> System.ArgumentException: Can not convert Array to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at GoogleTranslateFreeApi.GoogleTranslator.GetMainTranslationInfo(JToken translationInfo, String[]& translate, String& originalTextTranscription, String& translatedTextTranscription) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi\GoogleTranslator.cs:line 345
   at GoogleTranslateFreeApi.GoogleTranslator.ResponseToTranslateResultParse(String result, String sourceText, Language sourceLanguage, Language targetLanguage, Boolean additionInfo) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi\GoogleTranslator.cs:line 247
   at GoogleTranslateFreeApi.GoogleTranslator.GetTranslationResultAsync(String originalText, Language fromLanguage, Language toLanguage, Boolean additionInfo) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi\GoogleTranslator.cs:line 232
   at GoogleTranslateFreeApi.GoogleTranslator.TranslateAsync(String originalText, Language fromLanguage, Language toLanguage) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi\GoogleTranslator.cs:line 132
   at GoogleTranslateFreeApi.Examples.Program.Translate(String text, String lang) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi.Examples\Program.cs:line 69
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task 1.GetResultCore(Boolean waitCompletionNotification)
   at GoogleTranslateFreeApi.Examples.Program.Main(String[] args) in D:\Temp Projects\GoogleTranslateFreeApi-master\GoogleTranslateFreeApi.Examples\Program.cs:line 42`

no matter whether my own code is fired or your examples from GoogleTranslateFreeApi.Examples are used.

I tried to debug the issue and found out that sometimes JSON result from [https://translate.google.com/translate_a/single](url)
depending on the original text provided differs in size. So in your GetMainTranslationInfo method in this block of code
```
foreach (var item in translationInfo)
{
	if (item.Count() == 5)
		translations.Add(item.First.Value<string>());
	else
	{
		var transcriptionInfo = item;
		int elementsCount = transcriptionInfo.Count();
		if (elementsCount == 3)
		{
			translatedTextTranscription = (string)transcriptionInfo[elementsCount - 1];
		}
		else
		{
			if (transcriptionInfo[elementsCount - 2] != null)
				translatedTextTranscription = (string)transcriptionInfo[elementsCount - 2];
			else
				translatedTextTranscription = (string)transcriptionInfo[elementsCount - 1];

			originalTextTranscription = (string)transcriptionInfo[elementsCount - 1];
		}
	}
}
```

when json result [0] [0] 's length isn't 5 but for example 8 like in this case:

![image](https://user-images.githubusercontent.com/50525749/60029327-9bdb7100-96a9-11e9-82bc-e4128539f7a4.png)

the check for `if (item.Count() == 5)` would not fire ending up with no translation, but 
`if (item.Count() >= 5)` will.

I did not look much into it though, so maybe you can come up with something more accurate.

Thank you in advance.

**Comment by Grizley56** [comment]
Hello, Viacheslav. I confess, that there is no free specification about response formats, therefore all cases was written through trial and error. I don't sure there is more accurate way, so i will fix it this way.
Thanks for contributing.
